import { Module } from '../../types';

export const frontDeskGreetings: Module = {
  id: 'frontdesk-greetings',
  title: 'Greetings & Check-in',
  blurb: 'Open the conversation, get a name, confirm the appointment, ask for ID and insurance.',
  available: true,
  phrases: [
    {
      id: 'g-1',
      en: 'Good morning, do you have an appointment?',
      es: 'Buenos días, ¿tiene cita?',
      region: 'general',
      speaker: 'staff',
      note: 'Default greeting. Switch to "Buenas tardes" after noon, "Buenas noches" after dark.',
    },
    {
      id: 'g-2',
      en: 'Yes, I have an appointment at ten with Dr. Ramos.',
      es: 'Sí, tengo cita a las diez con la doctora Ramos.',
      region: 'mx',
      speaker: 'patient',
      note: 'In MX/PR/DO, "la doctora" is normal even spoken quickly — don\'t skip the article.',
    },
    {
      id: 'g-3',
      en: "What's your full name?",
      es: '¿Cuál es su nombre completo?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-4',
      en: 'My name is María Carmen Rivera Santos.',
      es: 'Me llamo María Carmen Rivera Santos.',
      region: 'pr',
      speaker: 'patient',
      note: 'Two surnames are standard. The first is the father\'s, the second is the mother\'s. Don\'t drop one.',
    },
    {
      id: 'g-5',
      en: 'Can I see your ID and insurance card, please?',
      es: '¿Me puede mostrar su identificación y la tarjeta del seguro, por favor?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-6',
      en: "I don't have insurance right now.",
      es: 'Ahora mismo no tengo seguro.',
      region: 'pr',
      speaker: 'patient',
      note: '"Ahora mismo" is very Caribbean — common in PR/DO. MX speakers might say "en este momento".',
    },
    {
      id: 'g-7',
      en: 'No problem, we can still see you. Please fill out this form.',
      es: 'No hay problema, igual lo podemos atender. Por favor llene este formulario.',
      region: 'general',
      speaker: 'staff',
      note: '"Llenar" is universal for "fill out". "Rellenar" is more Spain.',
    },
    {
      id: 'g-8',
      en: 'Have a seat, the doctor will be with you shortly.',
      es: 'Tome asiento, el doctor lo atiende en un momentito.',
      region: 'mx',
      speaker: 'staff',
      note: '"Momentito" is warm and very common in MX. PR/DO speakers also say "ahorita" or "ahora".',
    },
    {
      id: 'g-9',
      en: 'Sorry, I\'m a little late — there was a lot of traffic.',
      es: 'Disculpe, llegué un poquito tarde, había mucho tráfico.',
      region: 'general',
      speaker: 'patient',
      note: 'In PR you\'ll also hear "tapón" for traffic jam. In DR, "tapón" too. In MX, "tráfico" or "embotellamiento".',
    },
    {
      id: 'g-10',
      en: "Don't worry, come in.",
      es: 'No se preocupe, pase.',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-11',
      en: 'Have you been here before?',
      es: '¿Ya había venido antes a esta clínica?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-12',
      en: 'No, this is my first time.',
      es: 'No, es mi primera vez.',
      region: 'general',
      speaker: 'patient',
    },
    {
      id: 'g-13',
      en: 'What\'s your date of birth?',
      es: '¿Cuál es su fecha de nacimiento?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-14',
      en: 'March 14th, 1978.',
      es: 'Catorce de marzo del setenta y ocho.',
      region: 'mx',
      speaker: 'patient',
      note: 'Spanish dates: day-month-year. Speakers often drop "mil novecientos" and just say "del setenta y ocho".',
    },
    {
      id: 'g-15',
      en: 'What\'s a good phone number to reach you?',
      es: '¿Cuál es un buen número de teléfono donde la podamos llamar?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-16',
      en: 'Are you here for yourself, or for a family member?',
      es: '¿Viene para usted o para un familiar?',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-17',
      en: 'I came with my son. He\'s the one with the appointment.',
      es: 'Vine con mi hijo, él es el de la cita.',
      region: 'do',
      speaker: 'family',
      note: 'Caribbean speakers often drop the "s" — you may hear "lo de la cita" instead of "los". Train your ear.',
    },
    {
      id: 'g-18',
      en: 'Okay, please have him sign in here.',
      es: 'Está bien, por favor que él firme aquí.',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-19',
      en: 'I\'m going to need to ask you some questions before the doctor sees you.',
      es: 'Le voy a hacer unas preguntas antes de que pase con el doctor.',
      region: 'general',
      speaker: 'staff',
    },
    {
      id: 'g-20',
      en: 'My Spanish isn\'t perfect — please be patient with me.',
      es: 'Mi español no es perfecto, por favor tenga paciencia conmigo.',
      region: 'general',
      speaker: 'staff',
      note: 'Honest, disarming, and patients almost always respond warmly.',
    },
  ],
  drills: [
    {
      id: 'd-1',
      situation: 'A new patient walks in. Greet them and ask if they have an appointment.',
      target: 'Buenos días, ¿tiene cita?',
      acceptableVariants: [
        'buenas tardes, ¿tiene cita?',
        'buenas, ¿tiene una cita?',
        'hola, ¿tiene cita con nosotros?',
      ],
      region: 'general',
      hint: 'Greeting + "do you have an appointment".',
    },
    {
      id: 'd-2',
      situation: 'Ask the patient for their full name.',
      target: '¿Cuál es su nombre completo?',
      acceptableVariants: ['¿me puede dar su nombre completo?', '¿su nombre completo, por favor?'],
      region: 'general',
    },
    {
      id: 'd-3',
      situation: 'Ask politely for their ID and insurance card.',
      target: '¿Me puede mostrar su identificación y la tarjeta del seguro, por favor?',
      acceptableVariants: [
        '¿me enseña su identificación y el seguro?',
        '¿me da su id y la tarjeta del seguro, por favor?',
      ],
      region: 'general',
      hint: 'Use "mostrar" or "enseñar" — both are fine.',
    },
    {
      id: 'd-4',
      situation: 'A patient says they have no insurance. Tell them it\'s no problem and to fill out a form.',
      target: 'No hay problema, igual lo podemos atender. Por favor llene este formulario.',
      acceptableVariants: [
        'no se preocupe, llene este formulario por favor',
        'está bien, igual lo atendemos. llene este formulario.',
      ],
      region: 'general',
    },
    {
      id: 'd-5',
      situation: 'Ask the patient to have a seat — the doctor will be with them shortly.',
      target: 'Tome asiento, el doctor lo atiende en un momentito.',
      acceptableVariants: [
        'siéntese, el doctor viene en un momento',
        'tome asiento, ya viene el doctor',
      ],
      region: 'mx',
    },
    {
      id: 'd-6',
      situation: 'Ask the patient for their date of birth.',
      target: '¿Cuál es su fecha de nacimiento?',
      acceptableVariants: ['¿me da su fecha de nacimiento?', '¿cuándo nació?'],
      region: 'general',
    },
    {
      id: 'd-7',
      situation: 'A patient apologizes for being late because of traffic. Reassure them and tell them to come in.',
      target: 'No se preocupe, pase.',
      acceptableVariants: ['no hay problema, pase', 'tranquilo, pase adelante'],
      region: 'general',
    },
    {
      id: 'd-8',
      situation: 'Tell the patient your Spanish isn\'t perfect and ask for patience.',
      target: 'Mi español no es perfecto, por favor tenga paciencia conmigo.',
      acceptableVariants: [
        'disculpe, mi español no es muy bueno, tenga paciencia',
        'mi español es regular, por favor sea paciente conmigo',
      ],
      region: 'general',
    },
  ],
  scenarios: [
    {
      id: 's-1',
      title: 'New patient, walk-in, no insurance',
      setup:
        'A first-time patient walks in. They\'re a little nervous, no insurance, came on the bus. You need to greet them, get basic info, and get them seated.',
      persona:
        'You are Doña Carmen Rivera, 62, from Bayamón, Puerto Rico, now living in Wilmington DE. You\'ve never been to this clinic before. You came because your daughter said you should talk to someone — you\'ve been feeling "los nervios" badly. You don\'t have insurance right now. You speak no English. You\'re polite but anxious. Speak natural Caribbean Spanish — you drop final s\'s sometimes, you say "ahora mismo" and "pa\'" instead of "para". Don\'t use Castilian Spanish. Stay in character. If the user (the front-desk worker) asks something you don\'t understand, ask politely for them to repeat. Keep your responses to 1-3 sentences.',
      opener: 'Buenas, mija. Vengo porque mi hija me dijo que viniera. Es la primera vez que vengo aquí.',
      region: 'pr',
    },
    {
      id: 's-2',
      title: 'Family member checking in for adult son',
      setup:
        'A worried mother is checking in her 28-year-old son for his appointment. He\'s sitting in the lobby. You need to confirm the appointment and explain that he has to sign himself in.',
      persona:
        'You are Sra. Hernández, 54, originally from Guadalajara, Mexico, living in Newark DE. Your son Javier has an appointment with Dr. Patel at 2pm. He\'s 28 and has been struggling — depression, you think. You\'re used to handling things for him and you don\'t fully understand why he has to sign in himself. Speak warm, polite Mexican Spanish. Use "doctor", "cita", "mijo". You may push back gently when told he must sign in alone. Stay in character. Keep responses to 1-3 sentences.',
      opener:
        'Buenas tardes, señorita. Vengo a registrar a mi hijo Javier. Tiene cita a las dos con el doctor Patel.',
      region: 'mx',
    },
    {
      id: 's-3',
      title: 'Patient running late, agitated',
      setup:
        'A patient comes in 25 minutes late, frustrated about traffic. You need to de-escalate, check them in, and find out if they can still be seen.',
      persona:
        'You are Luis Méndez, 41, from Santo Domingo, DR, living in Dover DE. You had a 9am appointment, it\'s now 9:25, and you\'re flustered — there was an accident on Route 1. You\'re not angry at the worker, you\'re angry at yourself and the situation, but it comes out as venting. Speak fast, Dominican Spanish. Drop s\'s ("má" for "más"). Use "tapón" for traffic jam. Calm down quickly if the worker is kind. Keep responses to 1-3 sentences.',
      opener:
        '¡Ay, disculpe, disculpe! Sé que llegué tarde. Había un tapón tremendo en la Route 1, un accidente. ¿Todavía me pueden atender?',
      region: 'do',
    },
  ],
};
